### ISSUE TITLE
Generalise ProxMAAS for public consumption

### ISSUE THREAD

**Issue by Zorlin** [application-research/ehi-proxmaas#25]
It would be nice if this repo was friendlier for non-Estuary use cases.

```[tasklist]
### Tasks
- [ ] Clean up README
- [ ] Remove hard dependency on Technitium
- [ ] Expand README to cover more ground
```
